development:
  adapter: mysql2
  encoding: utf8
  database: rubydb
  username: rubyusr
  password: 12345678
  host: 85.10.205.173
  port: 3306
  
production:
  adapter: mysql2
  encoding: utf8
  database: rubydb
  username: rubyusr
  password: 12345678
  host: 85.10.205.173
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: rubydb
  username: rubyusr
  password: 12345678
  host: 85.10.205.173
  port: 3306